config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post 'instructors/:booking_id/accept', to: 'instructors#accept_booking', as: 'accept_booking'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :instructors do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:destroy]
  get 'confirmation/:booking_id', to: 'pages#confirmation', as: 'confirmation'
  get '/user/:id/dashboard', to: 'users#view_bookings', as: 'dashboard'
  get '/view_bookings', to: 'instructors#view_bookings', as: 'instructor_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instructor
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :user
  has_many :bookings

    include PgSearch::Model
    pg_search_scope :search_by_name_and_expertise,
      against: [ :first_name, :last_name, :expertise ],
      using: {
        tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :instructors
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @instructor = Instructor.find(params[:instructor_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @instructor = Instructor.find(params[:instructor_id])
    @booking.instructor = @instructor
    @booking.user = current_user

    if @booking.save
      redirect_to confirmation_path(@booking)
    else
      flash[:alert] = 'Something went wrong'
    end
  end

  def update

  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    if @booking.user.instructor
      redirect_to instructor_booking_path
    else
      redirect_to dashboard_path(@booking.user)
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :start_time, :duration, :price, :user_id, :instructor_id)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  # IMAGES = ["hUHzaiAHuUc", "EzH46XCDQRY", "E6ExxeQNiN4", "iE71-TMrrkE", "9fByQORuvqM", "IrRbSND5EUc", "tXJhAFVOHVk", "rM6tUdA8UyE"]

  def index
    if params[:query].present?
      @instructors = Instructor.search_by_name_and_expertise(params[:query])

    else
      @instructors = Instructor.all
    end
    @images = ["hUHzaiAHuUc", "EzH46XCDQRY", "E6ExxeQNiN4", "iE71-TMrrkE", "9fByQORuvqM", "IrRbSND5EUc", "tXJhAFVOHVk", "rM6tUdA8UyE", "v9FQR4tbIq8", "SVfXlChg9HI", "UYG1U5wj3Tk", "Z9AU36chmQI"]
  end

  def new
    @instructor = Instructor.new(params[:id])
  end

  def create
    @instructor = Instructor.new(instructor_params)
    @instructor.user = current_user
    @instructor.first_name = current_user.first_name
    @instructor.last_name = current_user.last_name
    @instructor.profile_url = current_user.profile_url
    @instructor.user.instructor = true
    if @instructor.save
      redirect_to instructor_booking_path
    else
      flash[:message] = @instructor.errors.full_messages
      render :new
    end
  end

  def show
    @instructor = Instructor.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def view_bookings
    @instructor = current_user.instructors.first
    @bookings = @instructor.bookings
  end

  def accept_booking
    @booking = Booking.find(params[:booking_id])
    @booking.accepted = true
    @booking.save
    redirect_to instructor_booking_path
  end

  private

  def instructor_params
    params.require(:instructor).permit(:first_name, :last_name, :expertise, :price, :bio)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def confirmation
    @booking = Booking.find(params[:booking_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
    @user = User.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def view_bookings
    @user = User.find(params[:id])
    @bookings = @user.bookings
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <h1>Book Your Session!</h1><br>
  <%# <div class="row justify-content-center"> %>

    <%= flash[:message] %>
      <%# <%= form_for [@instructor, @booking] do |f| %>
      <%= simple_form_for [ @instructor, @booking ] do |f| %>
      <%= f.input :price, label: "Duration" %>
      <%= f.input :date %>
      <%= f.input :start_time %>
      <%# <%= f.input :end_time %>

      <%= f.button :submit, class: "button" %><% end %>
  <%# </div> %>
</div>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/instructors/index.html.erb
<div class="container mt-4">
  <%= form_tag instructors_path, method: :get do %>
    <div class="row">
      <div class="form-group find-instructor pr-3">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find an instructor"
        %>
      </div>
      <div class="form-group">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

  <div class="cards-box">
    <div class="cards">
      <% @instructors.each do |instructor| %>
        <div class="card" style="width: 18rem;">
          <% if instructor.cover_url.nil? %>
            <%= image_tag 'https://source.unsplash.com/IuLgi9PWETU', alt: "card image", class: "card-img-top", style: "height: 220px"%>
          <% else %>
            <%= image_tag instructor.cover_url, alt: "card image", class: "card-img-top", style: "height: 220px"%>
          <% end %>
          <div class="card-body">
            <div class="card-body-text">
              <h5 class="card-title"><%= instructor.first_name %> <%= instructor.last_name %></h5>
              <p class="card-text">Expertise: <%= instructor.expertise %></p>
            </div>
            <div class="card-footer-price">
              <%= link_to 'See profile', instructor_path(instructor), class: "button" %>
              <div class="price">
                <h5><%="£ #{instructor.price}"%></h5>
                <p>/hour</p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/instructors/new.html.erb
<div class="container">
  <%# <div class="card"> %>
  <h1 style="text-align:center">Create an Instructor Profile</h1><br>
    <%# <div class="row justify-content-center"> %>
  <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
        <%= simple_form_for [ @instructor ] do |f| %>
        <%= f.input :expertise, label: "Expertise" %>
        <%= f.input :price, label: "Price per hour" %>

        <%= f.input :bio, label: "Bio" %>

        <%= f.button :submit, class: "button"%>
        <% end %>
    <%# </div> %>
  <%# </div> %>
</div>

app/views/instructors/show.html.erb
<section class="instructors">
  <div class="container-fluid">
    <div class="instructor-card pr-5">
      <h2 class="name"><%= @instructor.first_name %> <%= @instructor.last_name %></h2>
      <div class="instructor-cover mb-5" style="background-image: url('<%= @instructor.cover_url %>');">
        <div class="instructor-card-image">
          <% if @instructor.profile_url.nil? %>
            <img src="https://source.unsplash.com/480x480/?person,face" class="rounded-circle" alt="...">
          <% else %>
            <%= image_tag @instructor.profile_url, class: "rounded-circle" %>
          <% end %>
        </div>
      </div>
      <div class="card-content">
        <div class="instructor-card-text">
          <h3 class="expertise"><%= @instructor.expertise %></h3>
          <p class="description"><%= @instructor.bio %></p>
        </div>
      </div>
    </div>

    <div class="booking-card pl-3">
      <div class="divider"></div>
      <%= render partial: 'bookings/form' %>
    </div>
  </div>
</section>

app/views/instructors/view_bookings.html.erb
<div class="container">
  <div class="page-top">
    <h1>My profile</h1>
    <%= image_tag @instructor.profile_url, class: 'rounded-circle', style: "width: 150px" %>
    <h2><%= @instructor.bio %></h2>
  </div>
</div>


<div class="container">
  <h1>My bookings</h1>
  <div class="row">
    <div class="col flex">
      <% @bookings.each do |booking| %>
        <div class="booking-list">
          <div class="left-side">
            <%= image_tag booking.user.profile_url, class: 'avatar booking-list', style: 'width: 50px' %>
            <div class="text">
              <h6><strong><%= booking.user.first_name %> <%= booking.user.last_name %></strong> <%= booking.duration %> </h6>
              <h6>Date: <%= booking.date.to_time.strftime('%d/%m/%Y') %> | Time: <%= booking.start_time.to_time.strftime('%H:%M') %></h6>
            </div>
          </div>
          <div class="buttons">
            <% if booking.accepted %>
              <p class="accept">✔️Accepted</p>
              <%= link_to 'Cancel', booking_path(booking), class: 'button-sm', id: 'decline',  method: :delete %>
            <% else %>
              <%= link_to 'Accept', accept_booking_path(booking), method: :post, class: 'button-sm' %>
              <%= link_to 'Cancel', booking_path(booking), class: 'button-sm', id: 'decline',  method: :delete %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstructoProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/confirmation.html.erb
<div class="card-confirmation">
  <h1>Booking confirmed</h1>
  <h4>
    🎉 <strong><%= current_user.first_name %></strong>, your session is all booked up! 🎉
  </h4>
  <p>Date: <%= @booking.date.to_time.strftime('%d/%m/%Y') %>   |   Time: <%= @booking.start_time.to_time.strftime('%H:%M') %></p>
  <div class="buttons-inline">
    <%= link_to 'My bookings', dashboard_path(current_user), class: "button" %>
    <%= link_to 'Continue browsing', instructors_path, class: "button" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class='banner-container'>
  <div class="text">
    <h1>Instructo</h1>
    <h2>Connecting instructors and clients</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, distinctio error! Ratione quaerat eaque repellat. Sunt aut atque doloribus vitae quae nihil officia. Labore nostrum quo perspiciatis ducimus ratione eum.</p>
    <%= link_to 'Find an instructor', instructors_path, class: 'button' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/view_bookings.html.erb
<div class="container">
  <h1>My bookings</h1>
  <div class="row">
    <div class="col flex">
      <% @bookings.each do |booking| %>
        <div class="booking-list">
          <div class="left-side">
            <div class="text">
              <h6><strong><%= booking.instructor.first_name %> <%= booking.instructor.last_name %></strong></h6>
              <h6>Date: <%= booking.date.to_time.strftime('%d/%m/%Y') %> | Time: <%= booking.start_time.to_time.strftime('%H:%M') %></h6>
            </div>
          </div>
          <div class="buttons">
            <%= link_to 'Cancel', booking_path(booking), method: :delete, class: 'button-sm' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>